baseURL = "https://wiki.phala.network"
languageCode = "en-us"
title = "Phala Network Wiki"
theme = "compose"

defaultContentLanguage = "en-us"
defaultContentLanguageInSubdir= true

# # For search functionality
# [outputs]
# home = [ "HTML", "RSS", "JSON"]

#  menu items
[[menu.main]]
    name = "Docs"
    weight = 2
    url = "en-us/docs/"

[[menu.main]]
    name = "中文站"
    weight = 3
    url = "zh-cn/"

[[menu.main]]
    name = "French"
    weight = 4
    url = "fr-fr/"

[[menu.main]]
    name = "Homepage"
    weight = 5
    url = "https://phala.network"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  name = "Phala Network Wiki"
  repo = "https://github.com/Phala-Network/phala-wiki"
  editUrl = "https://github.com/Phala-Network/phala-wiki/edit/master/content/"
  [author]
    name = "Phala Network"
    url = "https://phala.network"

  # searchPlaceholder = "Search the docs ..."

  google_fonts = [
    ["Recursive", "300, 400, 500, 600"],
    ["Lato", "300, 400, 500, 600"],
  ]

  [params.logo]
    lightMode = "images/logo-phala-48.png"
    darkMode = "images/logo-phala-48.png"

  [params.source]
    name = "GitHub"
    icon = "github.svg"
    url = "https://github.com/Phala-Network/phala-wiki/"

[Languages]
  [Languages.en-us]
    title = "Phala Network Wiki"
    weight = 1
    languageName = "English"

  [Languages.zh-cn]
    title = "Phala Network 百科"
    weight = 2
    languageName = "简体中文"
  
  [Languages.fr-fr]
    title = "Phala Network Wiki"
    weight = 3
    languageName = "french"
